name: Build C++ Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Install C++ compiler and build tools
      - name: Install C++ compiler and build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ gcc cmake ninja-build pkg-config curl zip unzip tar

      # Setup vcpkg
      - name: Clone vcpkg
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - name: Setup vcpkg
        shell: bash
        run: |
          cd $VCPKG_ROOT
          ./bootstrap-vcpkg.sh -disableMetrics

      # Cache vcpkg packages
      - name: Cache vcpkg packages
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.VCPKG_ROOT }}/installed
            ${{ env.VCPKG_ROOT }}/packages
          key: vcpkg-ubuntu-${{ hashFiles('**/vcpkg.json', '**/vcpkg_manifest.json') }}
          restore-keys: vcpkg-ubuntu-

      # Set environment variables for compiler detection
      - name: Set compiler environment variables
        run: |
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV
          echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV
          echo "CMAKE_MAKE_PROGRAM=ninja" >> $GITHUB_ENV

      # Configure CMake
      - name: Configure CMake
        run: |
          cmake -B ${{ github.workspace }}/build -G Ninja -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake

      # Build
      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} --target streams_exec

      # Debug build issues if they occur
      - name: Debug on failure
        if: failure()
        run: |
          echo "==== Compiler versions ===="
          gcc --version
          g++ --version
          ninja --version
          echo "==== Build Log Contents ===="
          cat ${{ github.workspace }}/build/vcpkg-manifest-install.log || echo "Log file not found"
          echo "==== CMakeError.log ===="
          cat ${{ github.workspace }}/build/CMakeFiles/CMakeError.log || echo "Log file not found"
          echo "==== CMakeOutput.log ===="
          cat ${{ github.workspace }}/build/CMakeFiles/CMakeOutput.log || echo "Log file not found"

      # Find executable path
      - name: Find executable path
        id: find_exe
        shell: bash
        run: |
          EXEC_PATH="${{ github.workspace }}/build/streams/streams_exec"
          echo "Execute check if file exists"
          ls -la $(dirname "$EXEC_PATH") || echo "Directory not found"
          echo "executable_path=$EXEC_PATH" >> $GITHUB_OUTPUT

      # Upload artifact
      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: streams_exec-ubuntu
          path: ${{ steps.find_exe.outputs.executable_path }}