name: Build C++ Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl zip unzip tar cmake pkg-config build-essential g++ gcc

      - name: Clone vcpkg
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - name: Setup vcpkg
        run: |
          cd $VCPKG_ROOT
          ./bootstrap-vcpkg.sh -disableMetrics

      - name: Cache vcpkg packages
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.VCPKG_ROOT }}/installed
            ${{ env.VCPKG_ROOT }}/packages
          key: vcpkg-ubuntu-${{ hashFiles('**/vcpkg.json', '**/vcpkg_manifest.json') }}
          restore-keys: vcpkg-ubuntu-

      - name: Checkout folly
        run: git clone https://github.com/facebook/folly.git

      - name: Install folly dependencies
        run: |
          cd folly
          ./build/fbcode_builder/getdeps.py install-system-deps --recursive

      - name: Configure CMake
        run: |
          cmake -B ${{ github.workspace }}/build -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build Project
        run: cmake --build ${{ github.workspace }}/build --target streams_exec

      - name: Find executable path
        id: find_exe
        shell: bash
        run: |
          EXEC_PATH="${{ github.workspace }}/build/streams/streams_exec"
          echo "Execute check if file exists"
          ls -la $(dirname "$EXEC_PATH") || echo "Directory not found"
          echo "executable_path=$EXEC_PATH" >> $GITHUB_OUTPUT

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: streams_exec-ubuntu
          path: ${{ steps.find_exe.outputs.executable_path }}